issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/images-autodocs:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: chainguard-dev/images-autodocs/.github/workflows/autodocs-images.yaml@refs/heads/main

permissions:
  contents: write
  pull_requests: write
